### ISSUE TITLE
simplificaciones booleanas  

### ISSUE THREAD

**Issue by Maritza2893** [SistemasTecTlaxiaco/actividad-10-expresiones-boolenas-2363#1]
[Simplificaciones booleanas.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-expresiones-boolenas-2363/files/13608995/Simplificaciones.booleanas.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...

**Comment by JoseRodriguez-23620213** [comment]
Portada: 25
Procedimiento: 25
Figuras: 25
Resultados: 25
Calificación: 100 puntos = 10
Califico equipo Jose Antonio y Luis Alexis
